### ISSUE TITLE
Rethink on (mis)usage of the term "thunks"?

### ISSUE THREAD

**Issue by htaox** [htaox/durian#1]
@outvoider questions my use of the term thunks and implementation in the createThunk function.  Perhaps I should rename it as something more specific to durian because the signature is definitely unique to durian and not a general thunk since it does not return a callback or another thunk.

**Comment by htaox** [comment]
Updated any mentioning of ```thunks``` to ```actions```.  Creating "actions" is more specific to durian than a generalized function for creating thunks.

**Comment by outvoider** [comment]
see the file for my comments:

[action_hpp.txt](https://github.com/htaox/durian/files/217417/action_hpp.txt)
